#!/bin/python3
import math
import os
import random
import re
import sys

#
# Complete the 'plusMinus' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def plusMinus(arr):
    # Write your code here
    count_n=0
    count_p=0
    count0=0
    l= 0
    
    for num in arr:
        l = l+1
        if (num >0 and num <=100):
            count_p=count_p+1
        elif(num<0 and num >= -100):
            count_n=count_n+1
        elif(num ==0):
            count0=count0+1
        else:
            print("INPUT NO VALID")
    
    negative = count_n/l
    
    positive = count_p/l
    ceros = count0/l
    print(f'{positive}\n{negative}\n{ceros}')
                 
if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    plusMinus(arr)
